version: '3.8'

services:
  web:
    image: php:8.1-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=dbronnie
      - DB_USERNAME=root
      - DB_PASSWORD=Youth2025

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Youth2025
      MYSQL_DATABASE: dbronnie
      MYSQL_USER: dbronnie-user
      MYSQL_PASSWORD: Youth2025
    volumes:
      - mysql_data:/var/lib/mysql
      - ./radiant/database:/docker-entrypoint-initdb.d

volumes:
  mysql_data: